/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'primary-container': '#0061ff',
        'border-subtle': '#E2E8F0',
        'on-tertiary-fixed-variant': '#832700',
        'on-tertiary': '#ffffff',
        'on-secondary': '#ffffff',
        error: '#ba1a1a',
        'on-secondary-container': '#54647a',
        'on-surface-variant': '#424656',
        'on-primary': '#ffffff',
        'surface-container-high': '#e2e7ff',
        'inverse-surface': '#283044',
        'action-blue': '#0061FF',
        'surface-container-lowest': '#ffffff',
        'secondary-fixed-dim': '#b7c8e1',
        'on-secondary-fixed-variant': '#38485d',
        primary: '#004bca',
        secondary: '#505f76',
        'status-success': '#10B981',
        background: '#faf8ff',
        'tertiary-fixed-dim': '#ffb59d',
        'on-error': '#ffffff',
        'on-primary-container': '#f1f2ff',
        tertiary: '#9d3000',
        'surface-container-low': '#f2f3ff',
        'surface-container': '#eaedff',
        'on-surface': '#131b2e',
        'surface-card': '#FFFFFF',
        'status-warning': '#F59E0B',
        'secondary-container': '#d0e1fb',
        'on-primary-fixed-variant': '#003ea8',
        'on-primary-fixed': '#00174b',
        'tertiary-fixed': '#ffdbd0',
        outline: '#737687',
        'inverse-on-surface': '#eef0ff',
        'text-muted': '#64748B',
        'inverse-primary': '#b4c5ff',
        'surface-base': '#F8FAFC',
        'primary-fixed': '#dbe1ff',
        surface: '#faf8ff',
        'surface-container-highest': '#dae2fd',
        'surface-variant': '#dae2fd',
        'outline-variant': '#c2c6d9',
        'surface-bright': '#faf8ff',
        'tertiary-container': '#c73f00',
        'status-error': '#EF4444',
        'on-tertiary-container': '#ffefeb',
        'secondary-fixed': '#d3e4fe',
        'on-background': '#131b2e',
        'surface-dim': '#d2d9f4',
        'text-main': '#0F172A',
        'on-tertiary-fixed': '#390c00',
        'error-container': '#ffdad6',
        'primary-fixed-dim': '#b4c5ff',
        'on-error-container': '#93000a',
        'surface-tint': '#0052dc',
        'on-secondary-fixed': '#0b1c30',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'stack-md': '16px',
        'stack-lg': '24px',
        'stack-sm': '8px',
        'sidebar-width': '240px',
        gutter: '24px',
        'container-max': '1280px',
      },
      fontFamily: {
        'mono-label': ['JetBrains Mono'],
        'body-md': ['Inter'],
        'label-md': ['Inter'],
        'display-sm': ['Inter'],
        'body-sm': ['Inter'],
        'title-lg': ['Inter'],
        'headline-md': ['Inter'],
      },
      fontSize: {
        'mono-label': ['12px', { lineHeight: '16px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '500' }],
        'display-sm': ['24px', { lineHeight: '32px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'body-sm': ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'title-lg': ['16px', { lineHeight: '24px', fontWeight: '600' }],
        'headline-md': ['20px', { lineHeight: '28px', letterSpacing: '-0.01em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
};
